default: &default
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username: <%= ENV.fetch('DATABASE_USER') { 'root' } %>
    password: <%= ENV.fetch('DATABASE_PASSWORD') { 'password' } %>
    host: <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>
    port: <%= ENV.fetch('DATABASE_PORT') { 5432 } %>

development:
    <<: *default
    database: app_development

test:
    <<: *default
    database: app_test

production:
    <<: *default
    database: app_production
